SimilarityThreshold: 0.6
tags_per_item: 0  # 0 means no limit
tags:
  - 'chicken'
  - 'burger'
  - 'sushi'
  - 'pasta'
  - 'pizza'
  - 'poke'
  - 'salad'
  - 'fruits'
  - 'ramen'
  - 'beef'
  - 'juice'
  - 'drinks'
  - 'asian'
  - 'american'
  - 'italian'
  - 'chinese'
  - 'japanese'
  - 'soup'
  - 'prawn'
  - 'salmon'
  - 'seafood'
  - 'calzone'
  - 'arabic'
  - 'indian'
  - 'teriyaki'
  - 'thai'
