CHAIN_EMBEDDINGS = "embeddings"
COSINE_SIMILARITY = "cosine_similarity"
COSINE_SIMILARITY_RANK = "cosine_similarity_rank"
CHAIN_RANK = "chain_rank"
VENDOR_ID = "vendor_id"
CHAIN_ID = "chain_id"
CHAIN_NAME = "chain_name"
STATUS = "status"
FINAL_RANK = "final_rank"
ORIGINAL_RANK = "original_rank"
OFFLINE_AVERAGE_THRESHOLD = "offline_average_threshold"
# TODO Provide real values for below
MENU_ITEM_ID = "items_id"
MENU_ITEM_EMBEDDINGS = "embeddings"
MENU_ITEM_RANK = "menu_item_rank"
COUNTRY_CODE = "country"
MENU_SOURCE_SYSTEM_ITEM_ID = "source_system_item_id"
