import tensorflow as tf

CHAIN_FEATURE_COLUMNS = [
    "chain_profile_2t_v3_fv:tlabel",
    "chain_profile_2t_v3_fv:chain_freq_area_ids",
    "chain_profile_2t_v3_fv:chain_name",
    "chain_profile_2t_v3_fv:brand_id",
    "chain_performance_2t_v3_fv:chain_contact_pct",
    "chain_performance_2t_v3_fv:chain_actual_tpro_orders_pct",
    "chain_performance_2t_v3_fv:chain_avg_daily_active_orders_log",
    "chain_performance_2t_v3_fv:chain_avg_rating",
    "chain_performance_2t_v3_fv:chain_daily_orders_per_vendor_log",
    "chain_performance_2t_v3_fv:chain_avg_delivery_fee_eur",
    "chain_performance_2t_v3_fv:chain_fail_pct",
    "chain_performance_2t_v3_fv:chain_avg_incentive_pct",
    "chain_performance_2t_v3_fv:chain_incentivized_orders_pct",
    "chain_performance_2t_v3_fv:chain_log_avg_gmv_eur",
    "chain_performance_2t_v3_fv:chain_menu_to_cart_pct",
    "chain_performance_2t_v3_fv:chain_menu_to_order_pct",
    "chain_performance_2t_v3_fv:chain_new_order_pct",
    "chain_performance_2t_v3_fv:chain_potential_tpro_orders_pct",
    "chain_performance_2t_v3_fv:chain_tgo_orders_pct",
    "chain_menu_2t_v3_fv:chain_menu_desc_coverage_pct",
    "chain_menu_2t_v3_fv:chain_menu_image_coverage_pct",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_0",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_1",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_2",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_3",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_4",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_5",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_6",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_7",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_8",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_9",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_10",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_11",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_12",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_13",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_14",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_15",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_16",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_17",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_18",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_19",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_20",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_21",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_22",
    "chain_orders_2t_v3_fv:chain_hour_orders_pct_23",
]

ORDER_FEATURE_COLUMNS = [
    "order_profile_2t_v3_fv:delivery_area_id",
    "order_profile_2t_v3_fv:week_start",
    "order_profile_2t_v3_fv:geohash",
    "order_profile_2t_v3_fv:order_gmv_eur",
    "order_profile_2t_v3_fv:order_date",
    "order_profile_2t_v3_fv:order_time_utc",

    "account_orders_2t_v3_fv:most_recent_10_orders",  # user_prev_chains
    "account_orders_2t_v3_fv:frequent_chains",  # 'freq_chains'

    "account_search_2t_v3_fv:most_recent_15_search_keywords",  # prev_searches

    "account_performance_2t_v3_fv:account_log_order_cnt",
    "account_performance_2t_v3_fv:account_log_avg_gmv_eur",
    "account_performance_2t_v3_fv:account_incentives_pct",
    "account_performance_2t_v3_fv:account_is_tpro",
    "account_performance_2t_v3_fv:account_discovery_pct",

    "account_engagement_2t_v3_fv:most_recent_10_clicks_wo_orders",  # prev_clicks
    "account_engagement_2t_v3_fv:frequent_clicks",  # 'freq_clicks'
]


def get_feature_description(batch_size_positive, batch_size_negative):
    return {
        'chain_actual_tpro_orders_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_avg_daily_active_orders_log_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_avg_delivery_fee_eur_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_avg_incentive_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_avg_rating_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_contact_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_daily_orders_per_vendor_log_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_fail_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_freq_area_ids_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'chain_hour_orders_pct_0_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_1_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_10_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_11_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_12_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_13_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_14_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_15_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_16_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_17_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_18_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_19_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_2_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_20_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_21_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_22_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_23_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_3_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_4_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_5_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_6_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_7_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_8_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_hour_orders_pct_9_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_id_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'chain_incentivized_orders_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_log_avg_gmv_eur_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_menu_desc_coverage_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_menu_image_coverage_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_menu_to_cart_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_menu_to_order_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_name_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'chain_new_order_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_potential_tpro_orders_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_tgo_orders_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'tlabel_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'account_discovery_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'account_incentives_pct_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'account_is_tpro_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'account_log_avg_gmv_eur_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'account_log_order_cnt_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'delivery_area_id_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'freq_chains_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'freq_clicks_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'order_hour_pos': tf.io.FixedLenFeature([batch_size_positive], tf.int64),
        'order_weekday_pos': tf.io.FixedLenFeature([batch_size_positive], tf.int64),
        'geohash6_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'prev_clicks_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        'user_prev_chains_pos': tf.io.FixedLenFeature([batch_size_positive], tf.string),
        # 'brand_id_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'sample_weight_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'candidate_probability_pos': tf.io.FixedLenFeature([batch_size_positive], tf.float32),
        'chain_actual_tpro_orders_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_avg_daily_active_orders_log_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_avg_delivery_fee_eur_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_avg_incentive_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_avg_rating_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_contact_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_daily_orders_per_vendor_log_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_fail_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_freq_area_ids_neg': tf.io.FixedLenFeature([batch_size_negative], tf.string),
        'chain_hour_orders_pct_0_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_1_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_10_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_11_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_12_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_13_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_14_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_15_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_16_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_17_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_18_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_19_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_2_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_20_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_21_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_22_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_23_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_3_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_4_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_5_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_6_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_7_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_8_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_hour_orders_pct_9_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_id_neg': tf.io.FixedLenFeature([batch_size_negative], tf.string),
        'chain_incentivized_orders_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_log_avg_gmv_eur_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_menu_desc_coverage_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_menu_image_coverage_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_menu_to_cart_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_menu_to_order_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_name_neg': tf.io.FixedLenFeature([batch_size_negative], tf.string),
        'chain_new_order_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_potential_tpro_orders_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'chain_tgo_orders_pct_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
        'tlabel_neg': tf.io.FixedLenFeature([batch_size_negative], tf.string),
        'candidate_probability_neg': tf.io.FixedLenFeature([batch_size_negative], tf.float32),
    }
