extends: default

rules:
  document-start:
    present: false
  line-length:
    max: 120
    level: warning
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  truthy:
    check-keys: false
