version: 1
# See site-packages/bentoml/_internal/configuration/v1/default_configuration.yaml
tracing:
  sample_rate: 0.0
monitoring:
  # See site-packages/bentoml/_internal/monitoring/default.py
  enabled: false

api_server:
  metrics:
    enabled: false
  logging:
    access:
      enabled: false

runners:
  metrics:
    enabled: false
  logging:
    access:
      enabled: false
