name: Test

on:
  pull_request:
    branches: [ master, main, feat/* ]

env:
  GIT_REPO: ${{ github.event.repository.name }}
  STAGE: test
  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: secret
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_DEV }}
  SEMANTIC_CACHE_MODEL: ${{ secrets.SEMATIC_CACHE_MODEL }}
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_service_account.json
  S3_SERVER_PORT: 9002
  S3_SERVER_HOST: localhost
  S3_ACCESS_KEY: s3_access_key
  S3_SECRET_KEY: s3_secret_key
  S3_BUCKET_CONTENT_LOCAL_PATH: ./tests/fixtures/s3
  LOG_LEVEL: INFO

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Disabling shallow clone is required for SonarCloud to work properly
      - name: Set up GCP credentials
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          echo $GCP_SERVICE_ACCOUNT > /tmp/gcp_service_account.json
      - uses: actions/setup-python@v4
        with:
          # Pay attention to other places when changing the Python version
          python-version: '3.10'
          cache: pip
          cache-dependency-path: requirements-all.txt
      - uses: extractions/setup-just@v1
      - name: Install dependencies
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --quiet --yes postgresql-client
          just upgrade-pip
          pip install --disable-pip-version-check -r requirements-all.txt
      - name: Print prepared docker compose yaml file
        run: just test-docker-config
      - run: just set-up-tests-infra
      - run: just refresh-models
      - run: just run-tests-for-ci
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
